twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    form_themes: 
        - 'bootstrap_3_horizontal_layout.html.twig'
    strict_variables: '%kernel.debug%'
    globals:
        max_jobs_on_homepage: '%max_jobs_on_homepage%'
        
